server {
    listen 80;
    server_name _;
    root /var/www/html;
    index index.php;
    client_max_body_size 8m;

    location ^~ /data/ {
        deny all;
    }

    location ^~ /cache/ {
        deny all;
    }

    location ~ /\.(?!well-known) {
        deny all;
    }

    location = /index.css {
        try_files $uri =404;
    }

    location / {
        rewrite ^ /index.php last;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
    }
}
